/*
 * Diálogo PlanoGym
 */
package dialogos;


/**
 *
 * @author jaara
 */

public class DialogoPlanoGym extends javax.swing.JDialog {

    /**
     * Creates new form DialogoPlanoGym
     */
    private DialogoMaquina dialogoMaquina;
    
    public DialogoPlanoGym(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.dialogoMaquina=(DialogoMaquina) parent;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnZCardio = new javax.swing.JButton();
        btnZFuerza = new javax.swing.JButton();
        btnZEventos = new javax.swing.JButton();
        btnZPiernas = new javax.swing.JButton();
        btnZEntrada = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(999, 534));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(999, 534));
        getContentPane().setLayout(null);

        btnZCardio.setText("Zona Cardio");
        btnZCardio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZCardioActionPerformed(evt);
            }
        });
        getContentPane().add(btnZCardio);
        btnZCardio.setBounds(110, 190, 120, 23);

        btnZFuerza.setText("Zona Fuerza");
        btnZFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZFuerzaActionPerformed(evt);
            }
        });
        getContentPane().add(btnZFuerza);
        btnZFuerza.setBounds(710, 390, 120, 23);

        btnZEventos.setText("Eventos");
        btnZEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZEventosActionPerformed(evt);
            }
        });
        getContentPane().add(btnZEventos);
        btnZEventos.setBounds(240, 460, 72, 23);

        btnZPiernas.setText("Zona Piernas");
        btnZPiernas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZPiernasActionPerformed(evt);
            }
        });
        getContentPane().add(btnZPiernas);
        btnZPiernas.setBounds(430, 290, 120, 23);

        btnZEntrada.setText("Zona Entrada");
        btnZEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(btnZEntrada);
        btnZEntrada.setBounds(720, 150, 120, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/planoGYM.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1000, 588));
        jLabel2.setMinimumSize(new java.awt.Dimension(1000, 588));
        jLabel2.setPreferredSize(new java.awt.Dimension(1000, 588));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 1000, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    *   Métodos para establecer el texto al JField según JButton pulsado
    */
    private void btnZCardioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZCardioActionPerformed
        dialogoMaquina.textUbicacion.setText(btnZCardio.getText());
        dispose();
    }//GEN-LAST:event_btnZCardioActionPerformed

    private void btnZEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZEventosActionPerformed
        
        dialogoMaquina.textUbicacion.setText(btnZEventos.getText());
        dispose();
    }//GEN-LAST:event_btnZEventosActionPerformed

    private void btnZPiernasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZPiernasActionPerformed

        dialogoMaquina.textUbicacion.setText(btnZPiernas.getText());
        dispose();
    }//GEN-LAST:event_btnZPiernasActionPerformed

    private void btnZEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZEntradaActionPerformed
        
        dialogoMaquina.textUbicacion.setText(btnZEntrada.getText());
        dispose();
    }//GEN-LAST:event_btnZEntradaActionPerformed

    private void btnZFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZFuerzaActionPerformed
        
        dialogoMaquina.textUbicacion.setText(btnZFuerza.getText());
        dispose();
    }//GEN-LAST:event_btnZFuerzaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoPlanoGym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoPlanoGym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoPlanoGym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoPlanoGym.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoPlanoGym dialog = new DialogoPlanoGym(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnZCardio;
    private javax.swing.JButton btnZEntrada;
    private javax.swing.JButton btnZEventos;
    private javax.swing.JButton btnZFuerza;
    private javax.swing.JButton btnZPiernas;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
