/*
 * JFrame Form del inicio del programa
 */
package visualGrafica;

import dialogos.DialogoCarga;

/**
 *
 * @author jaara
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public inicio() {
        initComponents();
        this.setSize(770, 510);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        seleccionClase = new javax.swing.JComboBox<>();
        botonAceptar = new javax.swing.JButton();
        fondoImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Gestión del GYM JJ S.L.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 30, 340, 46);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione la tabla a gestionar");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 150, 260, 25);

        seleccionClase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seleccionClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personas", "Trabajadores", "Clientes", "Productos", "Eventos", "Máquinas" }));
        getContentPane().add(seleccionClase);
        seleccionClase.setBounds(340, 150, 350, 26);

        botonAceptar.setBackground(new java.awt.Color(229, 229, 229));
        botonAceptar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAceptar);
        botonAceptar.setBounds(610, 300, 100, 32);

        fondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/basiceditada.png"))); // NOI18N
        getContentPane().add(fondoImagen);
        fondoImagen.setBounds(0, 0, 770, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
     * Boton para que aparezca un pequeño diálogo de carga
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        DialogoCarga dialogoCarga = new DialogoCarga();
        dialogoCarga.setClase(seleccionClase.getSelectedItem().toString());
        dialogoCarga.setVisible(true);
        dispose();  //  Cierra la ventana actual
    }//GEN-LAST:event_botonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel fondoImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JComboBox<String> seleccionClase;
    // End of variables declaration//GEN-END:variables
}
